name: CI - FSOCO tools installation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PIP dependencies
        working-directory: ./tools
        run: |
          pip install --upgrade pip wheel
          pip install setuptools==60.8.2
          pip install --editable .

      - name: Install Supervisely SDK
        working-directory: ./tools
        run: pip install --editable .[sly]

      - name: Test execution (user)
        run: fsoco --help

      - name: Install development dependencies
        working-directory: ./tools
        run: |
          pip install -r requirements.txt
          pre-commit install

      - name: Test execution (developer)
        run: fsoco --help
