name: CI - FSOCO tools installation

on: [workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install dependencies
        working-directory: ./tools
        run: |
          pip install --upgrade pip setuptools
          pip install --editable .[sly]

      - name: Test execution
        run: fsoco --help
